name: SoulJars
version: ${project.version}
author: TheBusyBiscuit
website: http://TheBusyBiscuit.github.io/

main: io.github.thebusybiscuit.souljars.SoulJars
depend: [CS-CoreLib, Slimefun]
softdepend: [EmeraldEnchants]

api-version: 1.13
