name: SoulJars
version: ${project.version}
author: mrCookieSlime
website: http://TheBusyBiscuit.github.io/

main: me.mrCookieSlime.SoulJars.SoulJars
depend: [CS-CoreLib, Slimefun]
softdepend: [EmeraldEnchants]

api-version: 1.13
